### ISSUE TITLE
Support Optimize on non-append-only tables

### ISSUE THREAD

**Issue by wjones127** [delta-io/delta-rs#1125]
# Description

We note here that optimize only works on append-only tables. We should get it to work for all tables.

https://github.com/delta-io/delta-rs/blob/2c66b1937bd89e2de5b3d44aa3e2d2f562465901/rust/src/optimize.rs#L7-L8

**Use Case**

**Related Issue(s)**

**Comment by Matthieusalor** [comment]
Do we have more details on scenarios where the table might get corrupted besides when the table uses deletion vectors ?

**Comment by roeap** [comment]
Don't quite remember what the specific issue was when this was created. My assumption would be that the corruption was due to the fact that we were not doing conflict resolution on failing commits. This would not have been an issue for append only tables.

Since then we added conflict resolution, but not sure if that is in the latest python release. So i think this could be resolved now.

**Comment by wjones127** [comment]
I think we can consider this fixed by https://github.com/delta-io/delta-rs/pull/632, but we need to update the documentation for Optimize, since it currently claims it could corrupt tables.
