### ISSUE TITLE
WARN  Could not load all certificates - BadDER

### ISSUE THREAD

**Issue by kukushking** [delta-io/delta-rs#1224]
# Environment

**Delta-rs version**: 0.8.0

**Binding**:  Python (3.10.8)

**Environment**:
- **Cloud provider**: AWS
- **OS**: OSX
- **Other**:

***
# Bug

**What happened**:
After [upgrading](https://github.com/aws/aws-sdk-pandas/pull/2110) to 0.8.0, all operations display the following warning:
```
[2023-03-15T09:59:13Z WARN  hyper_rustls::connector] Could not load all certificates: Custom { kind: InvalidData, error: Custom { kind: InvalidData, error: BadDER } }
```

Looks like deltalake is not able to load certificates in the native OSX truststore. I do have a few unsigned/self-signed certs in my truststore so that might be it, but in that case I'd expect a message saying it's not able to validate it, not "bad" cert.

**What you expected to happen**:

**How to reproduce it**:

**More details**:

**Comment by wjones127** [comment]
Thanks for reporting this. We switched the default our build system from openssl to rustls, but it wasn't entirely intentional to switch the Python package.

I think we should switch back in the next version. If need be, I can do a bugfix release that switches back too.

There are some workarounds for MacOS described here: https://github.com/rustls/rustls/issues/127#issuecomment-691716887 Does that fix it for you?
