### ISSUE TITLE
Handling PyDeltaTableError throws a 500 Internal Server error response

### ISSUE THREAD

**Issue by mandyq1000** [delta-io/delta-rs#1284]
# Environment
python 3.9
**Delta-rs version**:
0.6.4
**Binding**: 
delta-rs python

**Environment**:
- **Cloud provider**: Azure
- **OS**: Mac OS Monterey
- **Other**: None

***
# Bug

**What happened**: We have an api endpoint that lets users pass in a path to a delta table and check if its a delta table, we are handling it in a try catch block and targeting PyDeltaTableError to be raised when the path points to something that is not a delta table, but instead of going inside the expect block PyDeltaTableError immediately throws a 500 internal server error.

**What you expected to happen**: We expect PyDeltaTableError to be handled and the control to reach within the block and return whatever is meant to be returned in the block.

**How to reproduce it**:
Simply have a try catch block that expects a PyDeltaTableError and then try to check if a path to a normal folder is an instance of DeltaTable, this should throw a PyDeltaTableError
EXAMPLE:
try:
     DeltaTable(<path_to_a_directory_that_is_not_a_delta_table>)
     return True
expect PyDeltaTableError:
     print("The control should reach here after the PyDeltaTableError is raised and print this line, but it doesn't")
     return False

**More details**:
<img width="766" alt="Screenshot 2023-04-13 at 10 37 14 PM" src="https://user-images.githubusercontent.com/56780989/231850675-1337aa65-3d8b-4927-a892-7ec23c366534.png">

**Comment by roeap** [comment]
Thanks for reporting @mandyq1000, Tried to reproduce the example, but there seems to be some more info required. This works for me - i.e. we are catching the right exception.

```py
from deltalake import DeltaTable, PyDeltaTableError

try:
    dt = DeltaTable("./not-present")
except PyDeltaTableError as e:
    print(e)
```

My suspicion would be we are either panicking, or raising something that is not a `PyDeltaTableError`. Unfortunately a 500 response from a server does not tell us much, since this is just the web server saying some thus far opaque thing went wrong.

Could you try catching any `Exception` and see what you are getting in the logs?

**Comment by mandyq1000** [comment]
Yes i got the logs I realised where the problem was. It's working as expected Thank You!
