### ISSUE TITLE
Investigate whether fsync system call is needed for fs backend atomic rename operation

### ISSUE THREAD

**Issue by houqp** [delta-io/delta-rs#142]
Rumor has that on Linux one needs to call fsync after temp file has been written out first before calling rename syscall, otherwise we could end up with an empty file in the new location during system crashes.

**Comment by ryan-johnson-databricks** [comment]
This is almost certainly true, because `rename` is a metadata-only operation. However, a call to [fdatasync](https://linux.die.net/man/2/fdatasync) should suffice because [rename](https://linux.die.net/man/2/rename) by virtue of being atomic must anyway sync all metadata needed to find and open the file (or at least, if there's a crash, the rename must have either succeeded or it did not).

**Comment by tsafacjo** [comment]
can I take it ?
