### ISSUE TITLE
[Python] Incorrect file URIs when partition values contain escape character

### ISSUE THREAD

**Issue by j-bennet** [delta-io/delta-rs#1533]
# Environment

**Delta-rs version**: 0.10.0

**Binding**: Python

**Environment**:
- **Cloud provider**:
- **OS**: macOS
- **Other**:

***
# Bug

**What happened**:

When partition values contain an escape character (example: `letter=%2F%2520%25f`), `deltalake` returns incorrect `file_uris` - they seem to have an additional level of urlencoding.

**What you expected to happen**:

`file_uris` to return uris that correspond to actual file names.

**How to reproduce it**:

1. Download data from Delta Acceptance Testing (https://github.com/delta-incubator/dat/)

`wget https://github.com/delta-incubator/dat/releases/download/v0.0.2/deltalake-dat-v0.0.2.tar.gz`

2. Extract the data.
3. Check `file_uris`:

```python
> ipython
In [1]: from deltalake import DeltaTable

In [2]: dt = DeltaTable("out/reader_tests/generated/multi_partitioned/delta")

In [3]: dt.file_uris()
Out[3]:
['/Users/jbennet/src/delta-rs/python/out/reader_tests/generated/multi_partitioned/delta/letter=%252F%252520%2525f/date=1970-01-01/data=hello/part-00000-a29a3f63-5a26-4127-aeff-e6d27c077917.c000.snappy.parquet',
 '/Users/jbennet/src/delta-rs/python/out/reader_tests/generated/multi_partitioned/delta/letter=b/date=1970-01-01/data=%F0%9F%98%88/part-00000-9363b3d0-34b9-4db4-baf6-9b48cf88ae5b.c000.snappy.parquet']
```

The actual paths do not correspond to returned urls:

```
In [4]: ! ls -l /Users/jbennet/src/delta-rs/python/out/reader_tests/generated/multi_partitioned/delta/
total 0
drwxr-xr-x  8 jbennet  staff  256 Jan 24 17:50 _delta_log
drwxr-xr-x  3 jbennet  staff   96 Jan 24 17:50 letter=%2F%2520%25f
drwxr-xr-x  3 jbennet  staff   96 Jan 24 17:50 letter=__HIVE_DEFAULT_PARTITION__
drwxr-xr-x  4 jbennet  staff  128 Jan 24 17:50 letter=a
drwxr-xr-x  4 jbennet  staff  128 Jan 24 17:50 letter=b
```

Actual path: `letter=%2F%2520%25f`
Returned by `delta-rs`: `letter=%252F%252520%2525f`

**More details**:

**Comment by sherlockbeard** [comment]
#1079 #1446

**Comment by tmrlvi** [comment]
It seems to be because the library uses `object_store::path:Path::from` instead of `object_store::path::Path::parse`.

When I look at the JSON written by the official pyspark library, the paths, at least in the `add` actions, are already encoded, and using `Path::from` farther encodes the encoded url. (And in the python implementation, `Path::from` is called twices, so it is double encoded)

From the [docs](https://docs.rs/object_store/latest/object_store/path/struct.Path.html#encode):
>A string containing potentially illegal path segments can be encoded to a [Path](https://docs.rs/object_store/latest/object_store/path/struct.Path.html) using [Path::from](https://docs.rs/object_store/latest/object_store/path/struct.Path.html#method.from) or [Path::from_iter](https://docs.rs/object_store/latest/object_store/path/struct.Path.html#method.from_iter).

Replacing all the `Path::from()` with `Path::parse().unwrap()` in `rust/src/table_state.rs` and in `python/src/filesystem.rs` seems to solve this issue, but:
1) I am not sure it does not introduce other issues
2) I am not sure how to handle errors gracefully in `file_paths_iter` (instead of unwrapping and crashing)
3) I did not test writing at all
