### ISSUE TITLE
Missing support for unsigned integer data types in SchemaDataType (Rust)

### ISSUE THREAD

**Issue by nholt01** [delta-io/delta-rs#1751]
# Description
[The schema data type enum](https://docs.rs/deltalake/latest/deltalake/schema/enum.SchemaDataType.html) doesn't seem to support unsigned integers. I was wanting to create a schema which stored u32 values, but this doesn't seem to be possible - the closest I can get is i32. Is this a missing datatype option, or am I misunderstanding documentation on how to go about creating this.

I can use the arrow crate's UInt32Array to make an array to store u32s and so I should be able to insert them, I just can't figure out how to define the schema to create a table with these data types.

Apologies if I overlooked something in the documentation.

**Use Case**
Any time a user is creating a delta table with an unsigned datatype.

**Comment by wjones127** [comment]
We only define types that are part of the [Delta Lake protocol](https://github.com/delta-io/delta/blob/master/PROTOCOL.md#primitive-types). This doesn't include unsigned integers, likely because it was written first by Java developers and Java doesn't have unsigned integers.

So I don't think we will be adding support for this.
