### ISSUE TITLE
Add operationMetrics to WRITE

### ISSUE THREAD

**Issue by r3stl355** [delta-io/delta-rs#1992]
# Description
Currently `WriteBuilder` does not collect the metrics as other operations do (e.g. `delete` or `merge`)

**Use Case**

**Related Issue(s)**

**Comment by gavinmead** [comment]
I'm interested in contributing to the project and can take a look at this one.  Thanks!

**Comment by gavinmead** [comment]
After reviewing the metrics implementations for Merge and Delete it should be easy enough to replicate the same things in write.  However, in [write.rs](https://github.com/delta-io/delta-rs/blob/main/crates/core/src/operations/write.rs#L761) the Output type for IntoFuture is a DeltaTable 

```rust
impl std::future::IntoFuture for WriteBuilder {
    type Output = DeltaResult<DeltaTable>;
```

and to conform to the other operations and surface the metrics it would change to:
```rust
impl std::future::IntoFuture for WriteBuilder {
    type Output = DeltaResult<(DeltaTable, WriteMetrics)>;
```

I just wanted to surface that since this "good first issue" may touch a fair amount of files 😄

**Comment by ion-elgreco** [comment]
@gavinmead you can do the first iteration where we just record the metrics in the commit but don't return them together with the DeltaTable instance
