### ISSUE TITLE
Unable to read s3 table: `Unknown scheme: s3`

### ISSUE THREAD

**Issue by rspears74** [delta-io/delta-rs#2065]
# Environment

**Delta-rs version**: `main` branch (I'm currently using this to develop because of bugs in datafusion 32, so I need datafusion 33+)

**Binding**: Rust

**Environment**:
- **Cloud provider**: AWS
- **OS**: MacOS/AWS Lambda
- **Other**:

***
# Bug

**What happened**:  `The specified table_uri is not valid: InvalidTableLocation("Unknown scheme: s3")` when trying to read a table with `open_table_with_storage_options`.

**What you expected to happen**: The table to be opened.

**How to reproduce it**: Try to read a table from s3 with `open_table_with_storage_options`. Something like this:
```
async fn read_table() -> Result<DeltaTable> {
    deltalake::open_table_with_storage_options(
        path,
        storage_options
    ).await?
}
```

**More details**: Yes, I am using the "s3" feature

**Comment by rtyler** [comment]
This is not a "bug" so much as a "feature" :smile: 

`main` has unreleased changes which fully remove the AWS support code into the deltalake-aws crate. In order to make that possible, the user must now let the core code what available storage handlers exist.  Here's an example of this being done in the Python code [here](https://github.com/delta-io/delta-rs/blob/main/python/src/lib.rs#L1505)

**Comment by rspears74** [comment]
Gotcha, thanks! I'll give this a shot!

**Comment by rspears74** [comment]
Looks like adding `deltalake::aws::register_handlers(None)` does the trick
