### ISSUE TITLE
convert to delta, add support for overwrite existing Table

### ISSUE THREAD

**Issue by djouallah** [delta-io/delta-rs#2097]
I have an external process that produce Parquet files incrementally, basically it just add files , I want to convert it to Delta Table , which currently works the first time but errors the second time as the table exists. 

two current workaround

- delete the log ( seems like hack)

- use arrow to write the delta table, I notice there is an overhead when transfering big volume of data and using batch next is slow

**Comment by ion-elgreco** [comment]
How would that be possible because you would have to  know which parquet files were actually valid parquets that belong to the parquet, since a delta table can also have parquets in there that we failed to commit..

You likely want to just manually add a transaction commit for these append actions if they are appends.

You could take a look at a tool @rtyler build: https://github.com/buoyant-data/oxbow
