### ISSUE TITLE
Add counter information to written parquet files

### ISSUE THREAD

**Issue by rtyler** [delta-io/delta-rs#262]
Based on the [comment by Serge](https://github.com/delta-io/delta-rs/pull/248#discussion_r637403171) the parquet file path generation could use some cleanup to track a counter, and rely on the parquet file's writer properties for determining whether to add a `snappy` or not.

**Comment by houqp** [comment]
Based on Serge's comment, we also need to use the same uuid for all files from the same batch, otherwise the counter won't provide any value.

**Comment by nfx** [comment]
https://github.com/apache/spark/blob/0494dc90af48ce7da0625485a4dc6917a244d580/sql/core/src/main/scala/org/apache/spark/sql/execution/streaming/ManifestFileCommitProtocol.scala#L115-L120 here's good enough reference on conventional filename formatting.

**Comment by Jan-Schweizer** [comment]
I think this issue is already done with this [PR](https://github.com/delta-io/delta-rs/pull/573). The [writer function](https://github.com/delta-io/delta-rs/blob/8fb89e08e99e96aad05c1eebf2cd9d271efa717b/crates/deltalake-core/src/writer/utils.rs#L111) `next_data_path` takes care of correctly constructing the path for a Parquet file.

**Comment by roeap** [comment]
You are correct @Jan-Schweizer - will close :)
