### ISSUE TITLE
Capture and send code coverage to codecov.io

### ISSUE THREAD

**Issue by nfx** [delta-io/delta-rs#266]
# Description

Sample implementation found at https://github.com/sevro/rust-codecov

Also as cargo ext https://github.com/kennytm/cargo-kcov

Technically, codecov doesn't need any GITHUB_TOKEN for public repos.

**Use Case**

Continuously measuring code quality and stability of connector. We should aim at 85% coverage, so that more people have confidence in using this repo.

**Comment by irishuangg** [comment]
👋 Hi this is my first OSS ever (most likely will comment questions here quite often)... interested in picking this up tho, as I need to sharpen my rust... are these still good instructions to follow?

**Comment by roeap** [comment]
Hi @irishuangg,

thanks for looking into this. Its been a while since I looked into coverage.io support for rust. I do seem to remember though that it used to rely on tests being run with nightly features. Thus i would recommend doing a bit of research on what the current state is, since its been a while since the ticket was originally opened.
