### ISSUE TITLE
Way to check if Delta table exists at specified path

### ISSUE THREAD

**Issue by jorritsandbrink** [delta-io/delta-rs#2662]
# Description
It would be nice to have a way to check if a Delta table exists at a given path.

Delta Spark has the `DeltaTable.isDeltaTable()` method: https://docs.delta.io/latest/api/python/spark/index.html#delta.tables.DeltaTable.isDeltaTable

**Use Case**
When merging into a Delta table, you first define a `DeltaTable` object before calling `merge` on it:

```py
dt = DeltaTable("path_to_table_that_may_not_exist_yet")

dt.merge(...)
```

This fails with a `TableNotFoundError` if the table does not exist.

Having the `isDeltaTable` method (or similar) would enable this flow:

```py
if DeltaTable.isDeltaTable("path_to_table_that_may_not_exist_yet"):
    dt = DeltaTable("path_to_table_that_may_not_exist_yet")
    dt.merge(...)
else:
    write_deltalake(...)
```

The above requires two path lookups, which adds unnecessary latency.

Alternatively, something like this could be nice:

```py
dt = DeltaTable("path_to_table_that_may_not_exist_yet", return_none_if_not_exists=True)

if dt is not None:
    dt.merge(...)
else:
    write_deltalake(...)
```

**Comment by omkar-foss** [comment]
Hey @jorritsandbrink, so there's a function called `try_get_deltatable()` in the code [here](https://github.com/delta-io/delta-rs/blob/main/python/deltalake/writer.py#L682) that provides this functionality. 

**`try_get_deltatable()`** returns `None` if the table is not found at the specified path (i.e. `TableNotFoundError` occurs), otherwise it returns the `DeltaTable` instance already existing at the specified path. It can be used with your above mentioned flow as follows:

```python

from deltalake.writer import try_get_deltatable

dt = try_get_deltatable("path_to_table_that_may_not_exist_yet")
if dt is not None:
    dt.merge(...)
else:
    write_deltalake(...)
```

And yes I agree with you, since this is a very common use case, we can abstract it to something more meaningful like `DeltaTable.isDeltaTable`.

Until then, I suppose we should consider adding the `try_get_deltatable` function to the delta-rs documentation, may help other users looking for this functionality.

**Comment by ion-elgreco** [comment]
Feel free to open a PR for a static method is_deltatable()

**Comment by omkar-foss** [comment]
take

**Comment by omkar-foss** [comment]
>Feel free to open a PR for a static method is_deltatable()

Hey @ion-elgreco @jorritsandbrink hope you both are doing great. I've opened PR #2715, please have a look whenever you get a chance. Thanks!
