### ISSUE TITLE
Use UV and Justfiles

### ISSUE THREAD

**Issue by ion-elgreco** [delta-io/delta-rs#2949]
# Description

We need to switch to UV for python, which will improve build times and venv creation times and swap Makefile out with a Justfile for simplicity.

**Related Issue(s)**

**Comment by rtyler** [comment]
I'm not familiar with uv but I don't understand what makes Justfiles simple? I've seen a few before since I believe `@roeap likes the tool, but I don't understand the benefit over GNU/Make.

I tend to prefer GNU/Make because it's on every Linux and macOS (gmake) install by default, but I'm not married to it

**Comment by ion-elgreco** [comment]
> I'm not familiar with uv but I don't understand what makes Justfiles simple? I've seen a few before since I believe `@roeap likes the tool, but I don't understand the benefit over GNU/Make.
> 
> I tend to prefer GNU/Make because it's on every Linux and macOS (gmake) install by default, but I'm not married to it

I found the syntax more simple, and its written in Rust 😆🦀
