### ISSUE TITLE
Safe guard DeltaTableState using Rust's type system

### ISSUE THREAD

**Issue by houqp** [delta-io/delta-rs#461]
# Description

**Use Case**

Follow up for https://github.com/delta-io/delta-rs/pull/456#issuecomment-941926489.

When we call `process_action` on a particular DeltaTableState, we need to make sure the passed in actions do not cross commit boundaries. We can restructure our code to have the Rust compiler to guarantee this property for us at build time.

Here is what I have in mind:

* Move `process_action` and `DeltaTableState` into its own module
* Add two new methods: `DeltaTableState::from_commit` and `DeltaTableState::from_checkpoint`

Since `DeltaTableState` is moved into its own module, other part of the code base won't be able to mutate a table state with arbitrary actions. The `from_commit` and `from_checkpoint` methods make sure users won't be able to construct table states from actions across commit boundaries.

**Related Issue(s)**

**Comment by dispanser** [comment]
@houqp : Nice idea!

I can see how this creates initial `DeltaTableState` in a consistent manner and protects it from feeding arbitrary actions from multiple commits or in the wrong order etc. I assume the `merge` operation (or some equivalent functionality) is still required, because we'd still need to add new commits to existing state. 

I think we would be able to show / prove that a table state that is merged from two adjacent commits in the right order (i.e., commit `n` left, commit `n+1` right) would itself yield a correct table state (`left` could be a checkpoint, but it would probably work either way). However, merge would still be able to create inconsistent state if someone applies it improperly, e.g., calling it with the two commits flipped or non-adjacent calls (two adds for the same file, ...).

If we want to protect from this as well, maybe we can:
- have `DeltaTableState` track the _range_ of commits it is representing
  - checkpoints would have range `[0, n]` where `n` is the checkpoint commit number
  - a single commit would have range `[n, n]`
  - a merge from `n-1` and `n` would have `[n-1,n]`.
  - ...
- assert `merge` to only merge states where `left.state.range.end + 1 = right.state.range.start`

I may be overthinking this, though; your suggestion is already protecting us from accidental state modification via `process_action`, which is the bigger part.

PS: I'm a fan of property-based testing (e.g., via [proptest](https://lib.rs/crates/proptest)), a consistent table state could be a sweet target for such a test suite.

**Comment by houqp** [comment]
> I assume the merge operation (or some equivalent functionality) is still required,

Yes, merge is still required, what's proposed in this issue is just to make sure merge always receives a validate DeltaTableState.

> have DeltaTableState track the range of commits it is representing

I think this is a really cool idea!

> I think the only save merge operation is by sequentially combining the full table state with the next commit, in order.

Yes, you are right. This also restricts how much we can parallel the action apply :( I think it's fair to say we can only parallel action application by partitioning actions within a checkpoint or commit. In other words, state merge has to be executed sequentially following the commit version. But we can reconstruct a table state in parallel.

I am also a fan of property-based testing and I have been thinking of adopting protest for delta-rs too. We should totally do it :)
