### ISSUE TITLE
Cargo build issue

### ISSUE THREAD

**Issue by hustnn** [delta-io/delta-rs#677]
# Environment
mac
rustc 1.64.0-nightly (7665c3543 2022-07-06)

**Delta-rs version**:
Latest main branch

***
# Bug

**What happened**:

Cargo build get the belowing errors:
`error[E0252]: the name `tls` is defined multiple times`

and 

`error[E0599]: no function or associated item named `new` found for struct `hyper_rustls::HttpsConnector` in the current scope`

Anybody met this before? Thanks.

**What you expected to happen**:

**How to reproduce it**:

**More details**:

**Comment by wjones127** [comment]
I've encountered this but haven't found a way to solve it. It originates from the aws/delta-checkpoint folder, so I've been working around it by building from the sub-directories that I care about instead of at the top-level (that is, `cd rust && cargo build`). But it would be nice to get the top-level fixed.

See past discussion: https://delta-users.slack.com/archives/C013LCAEB98/p1654306625879469

**Comment by hustnn** [comment]
It works. Thanks.
