### ISSUE TITLE
Expose schema API in python binding

### ISSUE THREAD

**Issue by danielhaviv** [delta-io/delta-rs#77]
Does the reader use the Parquet files' metadata to infer the schema?
If so, relying on the Delta log that could improve performance for operations that require the schema (especially when there are a lot of files involved).

**Comment by houqp** [comment]
We are already reading schema from delta transaction log, see https://github.com/delta-io/delta-rs/blob/main/rust/src/delta.rs#L232. schemas from parquet itself are ignored. Are you experiencing any performance issue with regards to schema handling?

**Comment by danielhaviv** [comment]
Haven't run it in scale yet, but issue #72 came up when I was only trying to get the schema back, meaning that it had to access the files to return the schema (it might have done nothing with them, but they were still accessed).

**Comment by houqp** [comment]
#72 is a bug related to pyarrow integration. That part of the code runs after we loaded the transaction log and schema from delta table. If you are using the python binding, then we don't have the schema rust api (https://github.com/delta-io/delta-rs/blob/main/rust/src/delta.rs#L519-L524) exposed yet, which is probably why you had to do the pyarrow table conversion first. For pyarrow internally goes through all the files and reads the schema directly from parquet files if i recall correctly, since it has no concept of DeltaTable. All it gets is a list of partitioned files. If you are using Rust client, then you won't need to do that conversion.

I think the right thing to do in this case is to add a new python api in https://github.com/delta-io/delta-rs/blob/main/python/src/lib.rs to wrap around the rust schema api.

**Comment by houqp** [comment]
https://docs.rs/pyo3/0.13.2/pyo3/conversion/trait.ToPyObject.html trait should help make this conversion a lot easier to maintain for us.

**Comment by houqp** [comment]
Thanks to @fvaleye, DeltaTable object now has `schema` and `arrow_schema` methods.

**Comment by danielhaviv** [comment]
Awesome, thanks @fvaleye.
