### ISSUE TITLE
Parsing partitions only handles partitions on the leading edge of the file path

### ISSUE THREAD

**Issue by hayesgb** [delta-io/delta-rs#989]
# Environment

**Delta-rs version**: 0.6.4

**Binding**:  Python

**Environment**:
- **Cloud provider**: Local Filesystem
- **OS**:  MacOS

***
# Bug

When using the Python writer and writing a Pandas DataFrame whose index has been set, reading that DataFrame back does not return the same object.

**What happened**:

**What you expected to happen**:

**How to reproduce it**:

```
import deltalake
import pandas as pd
from dask.datasets import timeseries
from pandas.testing import assert_frame_equal

df = timeseries(dtypes= "floats": float, "ints": int, "strings": str}).compute()

#df = df.reset_index()
write_deltalake("test0.delta", df, partition_by=["strings"])
table = DeltaTable("test0.delta")
df2 = table.to_pandas()
assert_frame_equal(df, df2)

```

**More details**:

Uncommenting the `reset_index()` line allow this to pass.

When construction the pyarrow Table with `.from_pandas(preserve_index=False)` is the default behavior, but this operation appends the index column to the table, and it is not preserved when reconstructing the Pandas DataFrame.

Should we expect `deltalake` to raise an exception when trying to attempting to write a Pandas DataFrame with an index that is anything other than a named RangeIndex?

**Comment by roeap** [comment]
I am not entirely sure, but i believe the index is stored as metadata in the parquet file with some specifics only known to pandas. More generally speaking, since there are potentially multiple writers to a delta table and multiple versions of the data are tracked, reconstructing the index when reading is not really possible. Things get even more complex when you take common optimizations like bin packing / z-orering etc into account.

As such i believe the way to go is to add the index as a column to the table, and re-create it in the pandas dataframe if needed. That being said, we should probably mention this behavior in the docs or raise some meaningful errors to the users.

Then again I may be wrong, since it has been a while since i last worked with pandas seriously :).

**Comment by ion-elgreco** [comment]
As @roeap suggests there are better ways to solve this, since you also can't be sure this metadata is always passed through
