### ISSUE TITLE
Provide case-insensitive storage options in backend

### ISSUE THREAD

**Issue by fvaleye** [delta-io/delta-rs#999]
# Description
The S3 `storage_options` is case-sensitive for the moment (example: created with [`from_map`](https://github.com/delta-io/delta-rs/blob/main/rust/src/storage/s3.rs#L247), which could lead to not retrieve `storage_options` provided with lowercases parameters (example: from the Python binding using a simple `storage_options` dictionary).

# Use Case
Allow case-insensitive storage options to provide more flexibility to the user when passing the `storage_options` via parameters.

**Comment by roeap** [comment]
We updated the azure and gcp options to be case-insensitive, and I meant to get around to updating the s3 options as well. We should however review the options all together, since some of these no longer do anything since we switches to object_store. specifically, object store does not expose as many options for the http client.. however the lock client still uses rusoto, which may in fact honor these options, so it needs a bit of a deeper look what we want to expose.
